# version: "3.2"
# services:
#  azure-storage:
#    image: "arafato/azurite:2.2.2"
#    ports:
#      - 10000:10000
#      - 10001:10001
#    volume binding seems to be broken at the moment
#    seems like a docker issue with AD
#    volumes:
#      - type: bind
#        source: ./emulation/azure-storage/data
#        target: /opt/azurite/folder
  database:
    build: ./dev/emulation/database
    ports:
      - ${MSSQL_PORT}:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
